Added problem writing if required files are not generated by a step

diff --git a/models/drought/agws/analyze/01_event_identification b/models/drought/agws/analyze/01_event_identification
--- a/models/drought/agws/analyze/01_event_identification
+++ b/models/drought/agws/analyze/01_event_identification
@@ -14,6 +14,12 @@ FLOWCOL='obs_flow' # for now we assume the standard obs_flow from the previous w
 DATECOL='obs_date'
 echo "Calling: Rscript $META_MODEL_ROOT/scripts/usgs/event_identification.R \"$COVERAGE_FLOW_FILE\" \"$DATECOL\" \"$FLOWCOL\" \"FALSE\" \"$EVENTS_FILE\""
 Rscript $META_MODEL_ROOT/scripts/usgs/event_identification.R "$COVERAGE_FLOW_FILE" "$DATECOL" "$FLOWCOL" "FALSE" "$EVENTS_FILE"
+
+if [ ! -e "$EVENTS_FILE" ]; then
+  echo "Event identification failed; could not generated $EVENTS_FILE ... exiting. " > problem
+  exit 1
+fi
+
 # note: the install -D command create the destination directory path if it doesn't exist
 #echo "Running: install -D $EVENTS_FILE ${USGS_DATA_DIR}/agws/${EVENTS_FILE}"
 #install -D $EVENTS_FILE "${USGS_DATA_DIR}/agws/${EVENTS_FILE}"
diff --git a/models/drought/agws/analyze/02_baseflow_events b/models/drought/agws/analyze/02_baseflow_events
--- a/models/drought/agws/analyze/02_baseflow_events
+++ b/models/drought/agws/analyze/02_baseflow_events
@@ -15,6 +15,12 @@ DATECOL='Date'
 
 echo "Calling: Rscript $META_MODEL_ROOT/scripts/usgs/baseflow_events.R \"$EVENTS_FILE\" \"$DATECOL\" \"$FLOWCOL\" \"$coverage\" \"$BASEFLOW_EVENTS_FILE\" \"$SITENOCOL\" \"$BASEFLOW_MIN_EVENT_LENGTH\"" 
 Rscript $META_MODEL_ROOT/scripts/usgs/baseflow_events.R "$EVENTS_FILE" "$DATECOL" "$FLOWCOL" "$coverage" "$BASEFLOW_EVENTS_FILE" "$SITENOCOL" "$BASEFLOW_MIN_EVENT_LENGTH"
+
+if [ ! -e "$BASEFLOW_EVENTS_FILE" ]; then
+  echo "Baseflow event summary failed; could not generated $BASEFLOW_EVENTS_FILE ... exiting. " > problem
+  exit 1
+fi
+
 # note: the install -D command create the destination directory path if it doesn't exist
 #echo "Running: install -D $BASEFLOW_EVENTS_FILE ${USGS_DATA_DIR}/agws/${BASEFLOW_EVENTS_FILE}"
 #install -D $BASEFLOW_EVENTS_FILE "${USGS_DATA_DIR}/agws/${BASEFLOW_EVENTS_FILE}"
diff --git a/models/drought/agws/analyze/03_baseflow_stats b/models/drought/agws/analyze/03_baseflow_stats
--- a/models/drought/agws/analyze/03_baseflow_stats
+++ b/models/drought/agws/analyze/03_baseflow_stats
@@ -13,4 +13,10 @@ echo "Calling: Rscript $META_MODEL_ROOT/scripts/usgs/baseflow_stats.R \"$BASEFLO
 Rscript $META_MODEL_ROOT/scripts/usgs/baseflow_stats.R "$BASEFLOW_EVENTS_FILE" "FALSE" "$BASEFLOW_STATS_FILE"
 # note: the install -D command create the destination directory path if it doesn't exist
 echo "Running: install -D $BASEFLOW_STATS_FILE ${USGS_DATA_DIR}/agws/${BASEFLOW_STATS_FILE}"
+
+if [ ! -e "$BASEFLOW_STATS_FILE" ]; then
+  echo "Baseflow stats failed; could not generated $BASEFLOW_STATS_FILE ... exiting. " > problem
+  exit 1
+fi
+
 install -D $BASEFLOW_STATS_FILE "${USGS_DATA_DIR}/agws/${BASEFLOW_STATS_FILE}"
diff --git a/models/drought/agws/analyze/04_trim_events b/models/drought/agws/analyze/04_trim_events
--- a/models/drought/agws/analyze/04_trim_events
+++ b/models/drought/agws/analyze/04_trim_events
@@ -12,6 +12,12 @@ echo "Trimming baseflow events for ${coverage}"
 #cp ${USGS_DATA_DIR}/agws/${eventfile} ./
 echo "Calling: Rscript $META_MODEL_ROOT/scripts/usgs/bf_trimming.R \"$BASEFLOW_STATS_FILE\" \"$BASEFLOW_TRIM_FILE\""
 Rscript $META_MODEL_ROOT/scripts/usgs/bf_trimming.R "$BASEFLOW_STATS_FILE" "$BASEFLOW_TRIM_FILE"
+
+if [ ! -e "$BASEFLOW_TRIM_FILE" ]; then
+  echo "Baseflow trimming failed; could not generated $BASEFLOW_TRIM_FILE ... exiting. " > problem
+  exit 1
+fi
+
 # note: the install -D command create the destination directory path if it doesn't exist
 #echo "Running: install -D $BASEFLOW_TRIM_FILE ${USGS_DATA_DIR}/agws/${BASEFLOW_TRIM_FILE}"
 #install -D $BASEFLOW_TRIM_FILE "${USGS_DATA_DIR}/agws/${BASEFLOW_TRIM_FILE}"
diff --git a/models/drought/agws/analyze/05_trim_stats b/models/drought/agws/analyze/05_trim_stats
--- a/models/drought/agws/analyze/05_trim_stats
+++ b/models/drought/agws/analyze/05_trim_stats
@@ -13,6 +13,12 @@ echo "Analyzing finall trimmed baseflow events for ${coverage}"
 #cp ${USGS_DATA_DIR}/agws/${eventfile} ./
 echo "Calling: Rscript $META_MODEL_ROOT/scripts/usgs/bf_trimming_analysis.R \"$BASEFLOW_TRIM_FILE\" \"$BASEFLOW_TRIM_STATS_FILE\""
 Rscript $META_MODEL_ROOT/scripts/usgs/bf_trimming_analysis.R "$BASEFLOW_TRIM_FILE" "$BASEFLOW_TRIM_STATS_FILE"
+
+if [ ! -e "$BASEFLOW_TRIM_STATS_FILE" ]; then
+  echo "Baseflow stats for trimmed file failed; could not generated $BASEFLOW_TRIM_STATS_FILE ... exiting. " > problem
+  exit 1
+fi
+
 # note: the install -D command create the destination directory path if it doesn't exist
 echo "Running: install -D $BASEFLOW_TRIM_STATS_FILE ${USGS_DATA_DIR}/agws/${BASEFLOW_TRIM_STATS_FILE}"
 install -D $BASEFLOW_TRIM_STATS_FILE "${USGS_DATA_DIR}/agws/${BASEFLOW_TRIM_STATS_FILE}"
diff --git a/models/drought/agws/analyze/06_regression_df b/models/drought/agws/analyze/06_regression_df
--- a/models/drought/agws/analyze/06_regression_df
+++ b/models/drought/agws/analyze/06_regression_df
@@ -8,7 +8,10 @@ fi
 # BEGIN - actually loading local data
 
 echo "Summarizing recession coefficients for each baseflow events for ${coverage}"
-#eventfile="bf_events_${coverage}.csv"
-#cp ${USGS_DATA_DIR}/agws/${eventfile} ./
 echo "Calling: Rscript $META_MODEL_ROOT/scripts/usgs/baseflow_regression_df.R \"$BASEFLOW_TRIM_STATS_FILE\" $GAGEID \"$BASEFLOW_SUMMARY_PREQC_DF\""
 Rscript $META_MODEL_ROOT/scripts/usgs/baseflow_regression_df.R "$BASEFLOW_TRIM_STATS_FILE" "$GAGEID" "$BASEFLOW_SUMMARY_PREQC_DF"
+
+if [ ! -e "$BASEFLOW_SUMMARY_PREQC_DF" ]; then
+  echo "Baseflow summary failed; could not generated $BASEFLOW_SUMMARY_PREQC_DF ... exiting. " > problem
+  exit 1
+fi
diff --git a/models/drought/agws/analyze/07_AGWRC_Q_lm b/models/drought/agws/analyze/07_AGWRC_Q_lm
--- a/models/drought/agws/analyze/07_AGWRC_Q_lm
+++ b/models/drought/agws/analyze/07_AGWRC_Q_lm
@@ -12,3 +12,8 @@ echo "Identifying and analyzing baseflow events for ${coverage}"
 #cp ${USGS_DATA_DIR}/agws/${eventfile} ./
 echo "Calling: Rscript $META_MODEL_ROOT/scripts/usgs/baseflow_regression.R \"$BASEFLOW_SUMMARY_PREQC_DF\" $GAGEID \"$BASEFLOW_REGRESSION_PREQC_DF\""
 Rscript $META_MODEL_ROOT/scripts/usgs/baseflow_regression.R "$BASEFLOW_SUMMARY_PREQC_DF" "$GAGEID" "$BASEFLOW_REGRESSION_PREQC_DF"
+
+if [ ! -e "$BASEFLOW_REGRESSION_PREQC_DF" ]; then
+  echo "AGWRC regression failed; could not generated $BASEFLOW_REGRESSION_PREQC_DF ... exiting. " > problem
+  exit 1
+fi
diff --git a/models/drought/agws/analyze/08_lm_QC b/models/drought/agws/analyze/08_lm_QC
--- a/models/drought/agws/analyze/08_lm_QC
+++ b/models/drought/agws/analyze/08_lm_QC
@@ -10,6 +10,11 @@ echo "Calculating QC metrics on regression from previous step for ${coverage}"
 echo "Calling: Rscript $META_MODEL_ROOT/scripts/usgs/regression_QC.R \"$BASEFLOW_SUMMARY_PREQC_DF\" \"$BASEFLOW_REGRESSION_PREQC_DF\" $BASEFLOW_REGRESSION_DF"
 Rscript $META_MODEL_ROOT/scripts/usgs/regression_QC.R "${BASEFLOW_SUMMARY_PREQC_DF}" "${BASEFLOW_REGRESSION_PREQC_DF}" "${BASEFLOW_REGRESSION_DF}"
 
+if [ ! -e "$BASEFLOW_REGRESSION_DF" ]; then
+  echo "AGWRC regression QC failed; could not generated $BASEFLOW_REGRESSION_DF ... exiting. " > problem
+  exit 1
+fi
+
 # note: the install -D command create the destination directory path if it doesn't exist
 echo "Running: install -D $BASEFLOW_REGRESSION_DF ${USGS_DATA_DIR}/agws/${BASEFLOW_REGRESSION_DF}"
 install -D $BASEFLOW_REGRESSION_DF "${USGS_DATA_DIR}/agws/${BASEFLOW_REGRESSION_DF}"
diff --git a/models/drought/agws/analyze/09_lm_outliers b/models/drought/agws/analyze/09_lm_outliers
--- a/models/drought/agws/analyze/09_lm_outliers
+++ b/models/drought/agws/analyze/09_lm_outliers
@@ -10,6 +10,11 @@ echo "Looking for potential outliers in regression for ${coverage}"
 echo "Calling: Rscript $META_MODEL_ROOT/scripts/usgs/regression_outliers.R \"$BASEFLOW_SUMMARY_PREQC_DF\" \"$BASEFLOW_SUMMARY_DF\""
 Rscript $META_MODEL_ROOT/scripts/usgs/regression_outliers.R "$BASEFLOW_SUMMARY_PREQC_DF" "$BASEFLOW_SUMMARY_DF"
 
+if [ ! -e "$BASEFLOW_SUMMARY_DF" ]; then
+  echo "Event QC failed; could not generated $BASEFLOW_SUMMARY_DF ... exiting. " > problem
+  exit 1
+fi
+
 # note: the install -D command create the destination directory path if it doesn't exist
 echo "Running: install -D $BASEFLOW_SUMMARY_DF ${USGS_DATA_DIR}/agws/${BASEFLOW_SUMMARY_DF}"
 install -D $BASEFLOW_SUMMARY_DF "${USGS_DATA_DIR}/agws/${BASEFLOW_SUMMARY_DF}"
diff --git a/models/drought/agws/analyze/10_event_qc_metrics b/models/drought/agws/analyze/10_event_qc_metrics
--- a/models/drought/agws/analyze/10_event_qc_metrics
+++ b/models/drought/agws/analyze/10_event_qc_metrics
@@ -9,3 +9,8 @@ echo "Finding number of events for QC ${coverage}"
 
 echo "Calling: Rscript $META_MODEL_ROOT/scripts/misc/numevents_qc.R \"$BASEFLOW_SUMMARY_DF\" \"$NUMEVENTS_QC_DF\""
 Rscript $META_MODEL_ROOT/scripts/misc/numevents_qc.R $BASEFLOW_SUMMARY_DF $NUMEVENTS_QC_DF
+
+if [ ! -e "$NUMEVENTS_QC_DF" ]; then
+  echo "General QC failed; could not generated $NUMEVENTS_QC_DF ... exiting. " > problem
+  exit 1
+fi
diff --git a/models/drought/agws/analyze/11_gage_qc_metrics b/models/drought/agws/analyze/11_gage_qc_metrics
--- a/models/drought/agws/analyze/11_gage_qc_metrics
+++ b/models/drought/agws/analyze/11_gage_qc_metrics
@@ -9,3 +9,8 @@ echo "Finding number of non-NA flow for ${coverage}"
 
 echo "Calling: Rscript $META_MODEL_ROOT/scripts/misc/filelength_qc.R \"$GAGEID\" \"$COVERAGE_FLOW_FILE\" \"$GAGE_QC_DF\""
 Rscript $META_MODEL_ROOT/scripts/misc/filelength_qc.R $GAGEID $COVERAGE_FLOW_FILE $GAGE_QC_DF
+
+if [ ! -e "$GAGE_QC_DF" ]; then
+  echo "General QC failed; could not generated $GAGE_QC_DF ... exiting. " > problem
+  exit 1
+fi
diff --git a/models/drought/agws/analyze/12_watershed_slope b/models/drought/agws/analyze/12_watershed_slope
--- a/models/drought/agws/analyze/12_watershed_slope
+++ b/models/drought/agws/analyze/12_watershed_slope
@@ -13,3 +13,8 @@ echo "Finding watershed slope of ${coverage}"
 
 echo "Calling: Rscript $META_MODEL_ROOT/scripts/usgs/watershed_slope.R \"$GAGEID\" \"$WSHED_SLOPE_DF\""
 Rscript $META_MODEL_ROOT/scripts/usgs/watershed_slope.R $GAGEID $WSHED_SLOPE_DF
+
+if [ ! -e "$WSHED_SLOPE_DF" ]; then
+  echo "Watershed slope summary failed; could not generated $WSHED_SLOPE_DF ... exiting. " > problem
+  exit 1
+fi
diff --git a/models/drought/agws/download/01_obtain_flow b/models/drought/agws/download/01_obtain_flow
--- a/models/drought/agws/download/01_obtain_flow
+++ b/models/drought/agws/download/01_obtain_flow
@@ -16,6 +16,12 @@ outfile="${coverage}-flow.csv"
 
 echo "Calling: Rscript $META_MODEL_ROOT/scripts/river/usgsdata.R $gageid $outfile $USGS_VERSION"
 Rscript $META_MODEL_ROOT/scripts/river/usgsdata.R $gageid $outfile $USGS_VERSION
+
+if [ ! -e "$outfile" ]; then
+  echo "USGS data retrieval failed; could not generate $outfile ... exiting. " > problem
+  exit 1
+fi
+
 # note: the install -D command create the destination directory path if it doesn't exist
 echo "Running: install -D $outfile $COVERAGE_FLOW_FILE"
 install -D $outfile $COVERAGE_FLOW_FILE
