dont assume columns unless absolutely necessary

diff --git a/models/hspf_cbp6/land/analyze/01_land_export b/models/hspf_cbp6/land/analyze/01_land_export
--- a/models/hspf_cbp6/land/analyze/01_land_export
+++ b/models/hspf_cbp6/land/analyze/01_land_export
@@ -18,5 +18,11 @@ set image_file_path=$CBP_EXPORT_DIR/land/$scenario/images
 # START_YEAR and END_YEAR are set in model_config script
 # this is the wrong setup here. This export creates OM exports
 # which should be in a separate app or an optional step
-echo "om CSV: Rscript $MODEL_ROOT/run/export/wdm_export_flow.R $scenario $segment $START_YEAR $END_YEAR $CBP_EXPORT_DIR $MODEL_ROOT"
-Rscript $MODEL_ROOT/run/export/wdm_export_flow.R $scenario $segment $START_YEAR $END_YEAR $CBP_EXPORT_DIR $MODEL_ROOT
+if ( ! $?EXPORT_RUNOFF_OM ) then
+  echo "!!!! WARNING: Cannot Locate EXPORT_RUNOFF_OM"
+endif
+
+if ( $EXPORT_RUNOFF_OM == 1 ) then
+  echo "om CSV: Rscript $MODEL_ROOT/run/export/wdm_export_flow.R $scenario $segment $START_YEAR $END_YEAR $CBP_EXPORT_DIR $MODEL_ROOT"
+  Rscript $MODEL_ROOT/run/export/wdm_export_flow.R $scenario $segment $START_YEAR $END_YEAR $CBP_EXPORT_DIR $MODEL_ROOT
+endif
