fied path dicrepancy

diff --git a/models/raster_met/cpcsoil/download/02_download b/models/raster_met/cpcsoil/download/02_download
--- a/models/raster_met/cpcsoil/download/02_download
+++ b/models/raster_met/cpcsoil/download/02_download
@@ -7,11 +7,16 @@ fi
 echo "Loading cpcsoil_config from $cpcsoil_config"
 . $cpcsoil_config
 
-dfile="$BASE_URI/$datasource/$varkey"
+# use set -e to tell the script to exit if anything fails
+# this will prevent over-writing a previously successful download
+# if the download fails
+set -e
+
+dfile="$BASE_URI/$datasource/${varkey}.nc"
 #https://psl.noaa.gov/thredds/fileServer/Datasets/cpcsoil/soilw.mon.mean.nc
 echo "Downloading from "${dfile}
-echo "with: wget -c --timeout=3600 $dfile"
-wget -c --timeout=3600 $dfile
+echo "with: wget -c --tries=0 $dfile"
+wget -c --tries=0 $dfile
 
 #echo "In: cd $base_dir"
 #cd $base_dir
@@ -20,5 +25,6 @@ wget -c --timeout=3600 $dfile
 #echo "Running: ./get_nldas_data $yr $jday $yr"
 #./get_nldas_data $yr $jday $NLDAS_ROOT
 # stick it in the repo
+echo "Copying: install -D $tmp_dir/${varkey}.nc $MET_EXPORT_DIR/$scenario/$yr/$mo/${varkey}.nc"
 install -D $tmp_dir/${varkey}.nc $MET_EXPORT_DIR/$scenario/$yr/$mo/${varkey}.nc
 # Ex: install -D /tmp/today_1777053514_11030/soilw.mon.mean.nc /media/model/met/cpcsoil/2026/04/soilw.mon.mean.nc
